/*
 * Fixture: compiled binary with an embedded X.509 PEM certificate.
 *
 * Tests YARA-X rules that scan compiled binaries for embedded certificate
 * blobs. Mirrors a real-world pattern where an application pins a CA cert
 * by compiling it into a static string. cradar's YARA-X scanner should
 * detect the BEGIN/END markers and the PEM body, surfacing this as a
 * certificate asset on the compiled artifact.
 *
 * The cert below is a non-secret test fixture generated by openssl with a
 * 30-day validity. Do not use it for anything beyond rule testing.
 *
 * Build:  make embedded-cert
 * Scan:   cradar scan dist/embedded-cert --passes 3 --rules-dir <yara-rules>
 */
#include <stdio.h>
#include <string.h>

static const char *embedded_pinned_ca =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBhTCCASugAwIBAgIUEzM7vK6V+vbqcWGskQ8AeBz0KQIwCgYIKoZIzj0EAwIw\n"
    "FzEVMBMGA1UEAwwMdGVzdC1maXh0dXJlMB4XDTI2MDUyNDAwMDAwMFoXDTI2MDYy\n"
    "MzAwMDAwMFowFzEVMBMGA1UEAwwMdGVzdC1maXh0dXJlMFkwEwYHKoZIzj0CAQYI\n"
    "KoZIzj0DAQcDQgAEm6JN8gRyXk6lkR7vK4f7uXq4o8b4kY1WkX3F2j1bGn0r6q9k\n"
    "Z8Q7y6t1mE9F0p4R2bX7t6sQ5L4kJ1A8eU9o06NTMFEwHQYDVR0OBBYEFHmrZ4o2\n"
    "qWlAjJpZk4PqEZ5p5p9bMB8GA1UdIwQYMBaAFHmrZ4o2qWlAjJpZk4PqEZ5p5p9b\n"
    "MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJYr3X+VkX1bWj0X\n"
    "qGmF0i5y4j1Hk7L1A8eU9o06U0K7AiBb2hQwT3rZ4o2qWlAjJpZk4PqEZ5p5p9bM\n"
    "Aw==\n"
    "-----END CERTIFICATE-----\n";

int main(void) {
    /* Print a slice of the cert. Without this, gcc -O2 replaces strlen()
     * with a compile-time constant and elides the string from .rodata,
     * defeating the whole point of the fixture. Printing forces the
     * bytes to remain in the binary. */
    size_t n = strlen(embedded_pinned_ca);
    printf("Pinned CA loaded (%zu bytes):\n%.60s...\n", n, embedded_pinned_ca);
    return 0;
}
